"""add body_html and body_format to posts

Revision ID: 1f9d454d12d1
Revises: ed7a2a8a5229
Create Date: 2026-06-20 16:17:58.281270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9d454d12d1'
down_revision = 'ed7a2a8a5229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_format', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('body_format')

    # ### end Alembic commands ###
