"""Add body_html, body_format to Comment; expand body to Text

Revision ID: 4e190f09cfd6
Revises: 91aa23751e83
Create Date: 2026-06-14 22:03:29.200247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e190f09cfd6'
down_revision = '91aa23751e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('body_format', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('disabled', sa.Boolean(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('author_id')
        batch_op.drop_column('disabled')
        batch_op.drop_column('body_format')
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###
